name: Check

on:
  push:
    tags-ignore:
      - "*.*.*"
    branches-ignore:
      - "documentation"
  pull_request:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check style
        run: make check-style
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Clippy
        run: make clippy
