name: Check

on:
  push:
    tags-ignore:
      - "*.*.*"
    branches-ignore:
      - "documentation"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Check style
        run: cargo fmt --check
      - name: Build (default)
        run: cargo build
      - name: Build (logging)
        run: cargo build --features=logging
      - name: Build (tracing)
        run: cargo build --features=tracing
      - name: Test current source
        run: cargo test --all-features
      - name: Clippy
        run: cargo clippy --all-features --no-deps
